/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V5.04.
*        Compiled Jan  8 2010, 16:46:31
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: kedu4
* Dimensions:  14 * 6
* NumColors:   0
*
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned short ackedu4[] = {
  0x77DE, 0x6B5B, 0x4652, 0x318D, 0x3DF0, 0x4232, 0x4232, 0x4231, 0x4231, 0x4232, 0x4232, 0x3DF0, 0x35AE, 0x39CF,
  0x39CF, 0x3DF0, 0x6739, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x6F7B, 0x4A53, 0x4632,
  0x4632, 0x4A53, 0x6F7B, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x6F7B, 0x4A53, 0x4632,
  0x3DF0, 0x4632, 0x6F7B, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x6F7B, 0x4A53, 0x4632,
  0x6B5A, 0x5AD7, 0x3DF0, 0x3DF0, 0x56B6, 0x6339, 0x5F19, 0x5EF8, 0x5EF8, 0x5F19, 0x6339, 0x56B6, 0x3DF0, 0x3DF0,
  0x7FFF, 0x7FFF, 0x77BD, 0x6F7B, 0x6B5A, 0x6739, 0x6739, 0x6739, 0x6739, 0x6739, 0x6739, 0x6739, 0x6B5A, 0x6F7B
};

GUI_CONST_STORAGE GUI_BITMAP bmkedu4 = {
  14, /* XSize */
  6, /* YSize */
  28, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)ackedu4,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_BMP555
};

/* *** End of file *** */
