/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V5.04.
*        Compiled Jan  8 2010, 16:46:31
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: kedu3
* Dimensions:  14 * 6
* NumColors:   0
*
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned short ackedu3[] = {
  0x35CF, 0x35AE, 0x35AE, 0x3DF0, 0x4232, 0x4632, 0x4232, 0x3E11, 0x35CF, 0x35AE, 0x3DF0, 0x4E74, 0x5F18, 0x6319,
  0x4231, 0x4211, 0x52B5, 0x6F9C, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x739C, 0x6339, 0x56D6, 0x56D6, 0x5EF8, 0x6318,
  0x4231, 0x4211, 0x52B5, 0x6F9C, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x739C, 0x6339, 0x56D6, 0x56D6, 0x5EF8, 0x6318,
  0x4231, 0x4211, 0x52B5, 0x6F9C, 0x7FFF, 0x7FFF, 0x7FFF, 0x7FFF, 0x739C, 0x6339, 0x56D6, 0x56D6, 0x5EF8, 0x6318,
  0x3DF0, 0x39CF, 0x4232, 0x56B6, 0x6319, 0x673A, 0x6319, 0x5AF7, 0x52B6, 0x4A74, 0x4A53, 0x5295, 0x5EF8, 0x6318,
  0x6F7B, 0x6B5A, 0x6B5A, 0x6739, 0x6739, 0x6739, 0x6739, 0x6739, 0x6738, 0x6739, 0x6B5A, 0x739C, 0x7BDE, 0x7BDE
};

GUI_CONST_STORAGE GUI_BITMAP bmkedu3 = {
  14, /* XSize */
  6, /* YSize */
  28, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)ackedu3,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_BMP555
};

/* *** End of file *** */

