/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V5.04.
*        Compiled Jan  8 2010, 16:46:31
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: volform
* Dimensions:  11 * 7
* NumColors:   0
*
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned short acvolform[] = {
  0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE,
  0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE,
  0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE,
  0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE,
  0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE,
  0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE,
  0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE, 0x48EE
};

GUI_CONST_STORAGE GUI_BITMAP bmvolform = {
  11, /* XSize */
  7, /* YSize */
  22, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acvolform,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_BMP555
};

/* *** End of file *** */
