// Commented means default
// {MMP_PAD_PSTM_B0,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5100
// {MMP_PAD_PSTM_B1,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5101
// {MMP_PAD_PSTM_B2,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5102
// {MMP_PAD_PSTM_B3,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5103
// {MMP_PAD_PSTM_B4,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5104
// {MMP_PAD_PSTM_B5,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5105
// {MMP_PAD_PSTM_B6,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5106
// {MMP_PAD_PSTM_B7,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5107
// {MMP_PAD_PSTM_B8,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5108
// {MMP_PAD_PSTM_B9,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5109
// {MMP_PAD_PSTM_B10,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x510A
// {MMP_PAD_PSTM_B11,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x510B
// {MMP_PAD_PSTM_B12,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x510C
// {MMP_PAD_PSTM_B13,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x510D
// {MMP_PAD_PSTM_B14,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x510E
// {MMP_PAD_PSTM_B15,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x510F
// {MMP_PAD_PSTM_B16,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5110
// {MMP_PAD_PSTM_B17,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5111
// {MMP_PAD_PSTM_B18,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5112
// {MMP_PAD_PSTM_B19,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5113
// {MMP_PAD_PSTM_B20,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5114
// {MMP_PAD_PSTM_B21,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5115
// {MMP_PAD_PSTM_B22,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5116
// {MMP_PAD_PSTM_B23,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5117
// {MMP_PAD_PSTM_B24,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5118
// {MMP_PAD_PSTM_B25,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5119
// {MMP_PAD_PSTM_B26,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x511A
// {MMP_PAD_PSTM_B27,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x511B
// {MMP_PAD_PSTM_B28,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x511C
// {MMP_PAD_PSTM_B29,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x511D
// {MMP_PAD_PSTM_B30,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x511E
// {MMP_PAD_PSTM_B31,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x511F
// {MMP_PAD_PSTM_T0,      PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(1)}, // 0x5120
// {MMP_PAD_PSTM_T1,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5121
// {MMP_PAD_PSTM_T2,      PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(1)}, // 0x5122
// {MMP_PAD_PSTM_T3,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5123
// {MMP_PAD_PSTM_T4,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5124
// {MMP_PAD_PSTM_T5,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5125
// {MMP_PAD_PSTM_T6,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5126
// {MMP_PAD_PSTM_T7,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5127
// {MMP_PAD_PSTM_T8,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5128
// {MMP_PAD_PSTM_T9,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5129
// {MMP_PAD_PSTM_T10,     PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(1)}, // 0x512A
// {MMP_PAD_PSTM_T11,     PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(1)}, // 0x512B
// {MMP_PAD_PSTM_T12,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x512C
// {MMP_PAD_PSTM_T13,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x512D
// {MMP_PAD_PSTM_T14,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x512E
// {MMP_PAD_PSTM_T15,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x512F
// {MMP_PAD_PSTM_T16,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5130
// {MMP_PAD_PSTM_T17,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5131
// {MMP_PAD_PSTM_T18,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5132
// {MMP_PAD_PSTM_T19,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5133
// {MMP_PAD_PSTM_T20,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5134
// {MMP_PAD_PSTM_T21,     PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(1)}, // 0x5135
// {MMP_PAD_PSTM_T22,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5136
// {MMP_PAD_PSTM_T23,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5137
// {MMP_PAD_PSTM_T24,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5138
// {MMP_PAD_PSTM_T25,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5139
// {MMP_PAD_PSTM_T26,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x513A
// {MMP_PAD_PSTM_T27,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x513B
// {MMP_PAD_PSTM_T28,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x513C
// {MMP_PAD_PSTM_T29,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x513D
// {MMP_PAD_PSTM_T30,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x513E
// {MMP_PAD_PSTM_T31,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x513F
// {MMP_PAD_PSTM_T32,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5140
// {MMP_PAD_PSTM_T33,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5141
// {MMP_PAD_PSTM_T34,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5142
// {MMP_PAD_PSTM_T35,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5143
// {MMP_PAD_PSTM_T36,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5144
// {MMP_PAD_PSTM_T37,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5145
// {MMP_PAD_PSTM_T38,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5146
// {MMP_PAD_PSTM_T39,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5147
// {MMP_PAD_PSTM_T40,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5148
// {MMP_PAD_PSTM_T41,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5149
// {MMP_PAD_PSTM_T42,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x514A
// {MMP_PAD_PSTM_T43,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x514B
// {MMP_PAD_PSTM_T44,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x514C
// {MMP_PAD_PSTM_T45,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x514D
// {MMP_PAD_PSTM_T46,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x514E
// {MMP_PAD_PSTM_T47,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x514F
// {MMP_PAD_PSTM_T48,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5150
// {MMP_PAD_PSTM_T49,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5151
// {MMP_PAD_PSTM_T50,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5152
// {MMP_PAD_PSTM_T51,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5153
// {MMP_PAD_PSTM_T52,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5154
// {MMP_PAD_PSTM_T53,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5155
   {MMP_PAD_PBGPIO0,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x5160 GPIO10, (SIF2_CLK)
   {MMP_PAD_PBGPIO1,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x5161 GPIO11, (SIF2_CS_N)
   {MMP_PAD_PBGPIO2,      PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(3)}, // 0x5162 GPIO12, (SIF2_DO)
   {MMP_PAD_PBGPIO3,      PAD_SCHMITT_TRIG | PAD_PULL_UP   | PAD_OUT_DRIVING(0)}, // 0x5163 GPIO13, (SIF2_DI)
   {MMP_PAD_PBGPIO4,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(0)}, // 0x5164 GPIO14, (SIF_WP_N)
   {MMP_PAD_PBGPIO5,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(0)}, // 0x5165 GPIO15, (SIF_HOLD_N)
// {MMP_PAD_PBGPIO6,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x5166 GPIO16
// {MMP_PAD_PBGPIO7,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x5167 GPIO17
   {MMP_PAD_PBGPIO8,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(0)}, // 0x5168 GPIO18, USB_OUT_PWR_SW_PIN, (GS_FORCEON)
// {MMP_PAD_PBGPIO9,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x5169 GPIO19, (GPS_EN)
// {MMP_PAD_PBGPIO10,     PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x516A GPIO20
// {MMP_PAD_PBGPIO11,     PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x516B GPIO21
   {MMP_PAD_PBGPIO12,     PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(3)}, // 0x516C GPIO22, (CH_STATES)
// {MMP_PAD_PBGPIO13,     PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x516D GPIO23
// {MMP_PAD_PBGPIO14,     PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x516E GPIO24
   {MMP_PAD_PBGPIO15,     PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(0)}, // 0x516F GPIO25, USB_IN_DETECT_VBUS_PIN, (VBUS_DET)
// {MMP_PAD_PBGPIO16,     PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x51C0 GPIO26
   {MMP_PAD_PBGPIO17,     PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(3)}, // 0x51C1 GPIO27, (QUICK_CHR)
// {MMP_PAD_PBGPIO18,     PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x51C2 GPIO28
   {MMP_PAD_PBGPIO19,     PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(3)}, // 0x51C3 GPIO29, (GPS_RST)
// {MMP_PAD_PBGPIO20,     PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x51C4 GPIO30
// {MMP_PAD_PBGPIO21,     PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x51C5 GPIO31
   {MMP_PAD_PCGPIO0,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x5170 GPIO32, (SD_LK)
   {MMP_PAD_PCGPIO1,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x5171 GPIO33, (SD_CMD)
   {MMP_PAD_PCGPIO2,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x5172 GPIO34, (SD_DATA0)
   {MMP_PAD_PCGPIO3,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x5173 GPIO35, (SD_DATA1)
   {MMP_PAD_PCGPIO4,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x5174 GPIO36, (SD_DATA2)
   {MMP_PAD_PCGPIO5,      PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x5175 GPIO37, (SD_DATA3)
   {MMP_PAD_PCGPIO6,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x5176 GPIO38, (SD_CD$)
   {MMP_PAD_PCGPIO7,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(0)}, // 0x5177 GPIO39, DEVICE_GPIO_SD_POWER (SD_PWR_EN)
   {MMP_PAD_PCGPIO8,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(0)}, // 0x5178 GPIO40, KEY_GPIO_POWER (PWR_KEY_DET)
   {MMP_PAD_PCGPIO9,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x5179 GPIO41, POWER_EN_GPIO (PWR_OFF)
// {MMP_PAD_PCGPIO10,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x517A GPIO42
   {MMP_PAD_PCGPIO11,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(0)}, // 0x517B GPIO43, NCFG_WAKEUP_PIN (WF_WAKE)
   {MMP_PAD_PCGPIO12,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x517C GPIO44, (WF_CLK)
   {MMP_PAD_PCGPIO13,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x517D GPIO45, (WF_CMD)
   {MMP_PAD_PCGPIO14,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x517E GPIO46, (WF_D0)
   {MMP_PAD_PCGPIO15,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x517F GPIO47, (WF_D1)
   {MMP_PAD_PCGPIO16,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x5180 GPIO48, (WF_D2)
   {MMP_PAD_PCGPIO17,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x5181 GPIO49, (WF_D3)
// {MMP_PAD_PCGPIO18,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x5182 GPIO50
   {MMP_PAD_PCGPIO19,     PAD_NORMAL_TRIG  | 				 PAD_OUT_DRIVING(1)}, // 0x5183 GPIO51, (CT_RES)
   {MMP_PAD_PCGPIO20,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x5184 GPIO52, TOUCH_PANEL_INT_GPIO (CT_INT)
   {MMP_PAD_PCGPIO21,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(0)}, // 0x5185 GPIO53, NCFG_RESET_PIN (WF_RESET)
   {MMP_PAD_PCGPIO22,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x5186 GPIO54, (GPS_TX)
   {MMP_PAD_PCGPIO23,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x5187 GPIO55, (GPS_RX)
   {MMP_PAD_PCGPIO24,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x5188 GPIO56, (CT_I2C_CK)
   {MMP_PAD_PCGPIO25,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x5189 GPIO57, (CT_I2C_SDA)
// {MMP_PAD_PCGPIO26,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x518A GPIO58
// {MMP_PAD_PCGPIO27,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x518B GPIO59
// {MMP_PAD_PCGPIO28,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x518C GPIO60
// {MMP_PAD_PCGPIO29,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x518D GPIO61
// {MMP_PAD_PCGPIO30,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x518E GPIO62
// {MMP_PAD_PCGPIO31,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(1)}, // 0x518F GPIO63
// {MMP_PAD_PAGPIO0,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(2)}, // 0x5190 GPIO2, (DBG_TX)
   {MMP_PAD_PAGPIO1,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x5191 GPIO3, LED_GPIO_POWER, (R_LED_EN)
   {MMP_PAD_PAGPIO2,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x5192 GPIO4, LED_GPIO_CAMERA, (G_LED_EN)
// {MMP_PAD_PAGPIO3,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(2)}, // 0x5193 GPIO5
   {MMP_PAD_PAGPIO4,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x5194 GPIO6, LED_GPIO_REC_CAPTURE, (REC_LED)
// {MMP_PAD_PAGPIO5,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(2)}, // 0x5195 GPIO7
// {MMP_PAD_PAGPIO6,      PAD_SCHMITT_TRIG | PAD_PULL_UP   | PAD_OUT_DRIVING(2)}, // 0x5196 GPIO8, (DBG_RX)
// {MMP_PAD_PAGPIO7,      PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(2)}, // 0x5197 GPIO9
   {MMP_PAD_PHI2C_SCL,    PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(3)}, // 0x5198 GPIO0, (PMU_SCL)
   {MMP_PAD_PHI2C_SDA,    PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(3)}, // 0x5199 GPIO1, (PMU_SDA)
   {MMP_PAD_PI2S_SDO,     PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x519A GPIO101, (MODE_KEY)
   {MMP_PAD_PI2S_SCK,     PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x519B GPIO97, (SPK_OFF)
// {MMP_PAD_PI2S_WS,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(2)}, // 0x519C GPIO98
// {MMP_PAD_PI2S_SDI,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(2)}, // 0x519D GPIO99
   {MMP_PAD_PI2S_MCLK,    PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(2)}, // 0x519E GPIO100, (REC_KEY)
   {MMP_PAD_PSNR_MCLK,    PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(2)}, // 0x51A0 GPIO71, (SN_CLK_SI1)
   {MMP_PAD_PSNR_RST_N,   PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x51A1 GPIO70, (SN_RST1)
   {MMP_PAD_PSNR_VSYNC,   PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x51A2 GPIO76, (SN_SI2C_CLK2)
   {MMP_PAD_PSNR_HSYNC,   PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x51A3 GPIO77, (SN_SI2C_DAT2)
// {MMP_PAD_PSNR_PCLK,    PAD_SCHMITT_TRIG | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x51A4 GPIO75
   {MMP_PAD_PSNR_D15_6,   PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x51A5 GPIO81~90, it is PSNR data set 0
   {MMP_PAD_PSNR_SCK,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x51A6 GPIO72, (SN_SI2C_CLK1)
   {MMP_PAD_PSNR_SDA,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x51A7 GPIO73, (SN_SI2C_DAT1)
// {MMP_PAD_PSNR_SEN,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x51A8 GPIO74
   {MMP_PAD_PSNR_D5_0,    PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x51A9 GPIO91~96, it is PSNR data set 1
   {MMP_PAD_PSNR_RST_N_1, PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(3)}, // 0x51AA GPIO78, (SN_RST2)
   {MMP_PAD_PSNR_MCLK_1,  PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(0)}, // 0x51AB GPIO80, (SN_CLK_SI2)
// {MMP_PAD_PSNR_SEN_1,   PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(3)}, // 0x51AC GPIO79
   {MMP_PAD_PDGPIO0,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x51B0 GPIO64, (ARM_TCK)
   {MMP_PAD_PDGPIO1,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x51B1 GPIO65, (ARM_TMS)
   {MMP_PAD_PDGPIO2,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x51B2 GPIO66, (ARM_TDI)
   {MMP_PAD_PDGPIO3,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x51B3 GPIO67, (ARM_TRST)
   {MMP_PAD_PDGPIO4,      PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(1)}, // 0x51B4 GPIO68, (ARM_TDO)
   {MMP_PAD_PDGPIO5,      PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(1)}, // 0x51B5 GPIO69, (ARM_RTCK)
// {MMP_PAD_PMCLK,        PAD_SCHMITT_TRIG | PAD_PULL_UP   | PAD_OUT_DRIVING(0)}, // 0x51B8
// {MMP_PAD_PVER_ID0,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x51BA
// {MMP_PAD_PVER_ID1,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x51BB
// {MMP_PAD_PVER_ID2,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x51BC
// {MMP_PAD_PVER_ID3,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x51BD
// {MMP_PAD_PVER_ID4,     PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(0)}, // 0x51BE
   {MMP_PAD_PLCD_D15_0,   PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(2)}, // 0x51D0 GPIO102~117
   {MMP_PAD_PLCD_WE,      PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(2)}, // 0x51D1 GPIO118, (LCD_PCLK)
   {MMP_PAD_PLCD_A0,      PAD_NORMAL_TRIG  | PAD_PULL_DOWN | PAD_OUT_DRIVING(2)}, // 0x51D2 GPIO119, (LCD_HD)
   {MMP_PAD_PLCD_RD,      PAD_NORMAL_TRIG  | PAD_PULL_UP   | PAD_OUT_DRIVING(2)}, // 0x51D3 GPIO120, (LCD_VD)
   {MMP_PAD_PLCD_CS1,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(2)}, // 0x51D4 GPIO121, (LCD_RST)
   {MMP_PAD_PLCD_CS2,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(2)}, // 0x51D5 GPIO122, (LCD_SCK)
   {MMP_PAD_PLCD_FLM,     PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(2)}, // 0x51D6 GPIO123, (LCD_SDA)
   {MMP_PAD_PLCD_GPIO,    PAD_NORMAL_TRIG  |                 PAD_OUT_DRIVING(2)}, // 0x51D7 GPIO124, (LCD_CS)
   {MMP_PAD_PHDMI_SCL,    PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(3)}, // 0x51D8 GPIO125, (10K PULL UP 3V3)
   {MMP_PAD_PHDMI_SDA,    PAD_SCHMITT_TRIG |                 PAD_OUT_DRIVING(3)}, // 0x51D9 GPIO126, (10K PULL UP 3V3)
